// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimelyServerApp;

namespace TimelyServerApp.Migrations
{
    [DbContext(typeof(TimelyDBContext))]
    [Migration("20191019104304_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimelyServerApp.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Project name 1",
                            Note = "This is the first project"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Project name 2",
                            Note = "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Project name 3",
                            Note = "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Project name 4",
                            Note = "sometimes by accident, sometimes on purpose (injected humour and the like)"
                        });
                });

            modelBuilder.Entity("TimelyServerApp.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "design",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "design",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "development",
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "management",
                            ProjectId = 4
                        });
                });

            modelBuilder.Entity("TimelyServerApp.Entities.Tag", b =>
                {
                    b.HasOne("TimelyServerApp.Entities.Project", "Project")
                        .WithMany("Tags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
